import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const index = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const style = await readFile(new URL('../css/style.css', import.meta.url), 'utf8');
const main = await readFile(new URL('../js/main.js', import.meta.url), 'utf8');
const projectsSection = index.match(/<section[^>]+id="projects"[\s\S]*?<\/section>/i)?.[0];
const workSection = index.match(/<section[^>]+id="work-in-progress"[\s\S]*?<\/section>/i)?.[0];

assert.doesNotMatch(index, /class="hero-identity-card"/i, 'El hero no debe mostrar la ficha de identidad');
assert.doesNotMatch(index, /id="profilePortrait"|Retrato pendiente/i, 'El hero no debe reservar un retrato pendiente');
assert.match(main, /initHeroMotion\(prefersReducedMotion\)/, 'La entrada del hero debe tener un único inicializador');
assert.match(style, /\.monitor-wrapper\s*\{[^}]*width:\s*330px/i, 'El monitor debe crecer ligeramente');
assert.match(style, /\.monitor-screen\s*\{[^}]*min-height:\s*230px/i, 'La pantalla debe ganar presencia sin exagerar');
assert.match(style, /@keyframes\s+monitorFloat/i, 'El monitor debe tener una flotación sutil');
assert.match(style, /@keyframes\s+monitorScan/i, 'La pantalla debe tener un barrido sutil');
assert.ok(workSection, 'NEXUS debe tener una sección independiente');
assert.match(workSection, /NEXUS/i);
assert.match(workSection, /WORK IN PROGRESS/i);
assert.match(workSection, /Steam/i);
assert.match(workSection, /Epic Games/i);
assert.match(workSection, /GOG/i);
assert.doesNotMatch(workSection, /href=/i, 'NEXUS no debe fingir un demo o repositorio');
assert.ok(projectsSection, 'El grid de proyectos debe seguir existiendo');
assert.match(style, /\.projects-section\s*\{[^}]*max-width:\s*1200px/i, 'Proyectos debe aprovechar mejor el ancho disponible');
assert.match(style, /\.projects-grid\s*\{[^}]*gap:\s*1rem/i, 'Las tarjetas de proyectos deben respirar entre sÃ­');
assert.doesNotMatch(projectsSection, /NEXUS/i, 'NEXUS no debe verse como un proyecto terminado');
assert.match(index, /class="tech-group"/i, 'Technologies debe estar organizada por grupos');
assert.match(index, /Core \/ Development/i, 'Technologies debe identificar el grupo principal');
assert.match(style, /\.tech-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2,/i, 'Technologies debe distribuirse en columnas');
assert.doesNotMatch(style, /\.tech-group:first-child\s*\{\s*grid-row:\s*span 2/i, 'Technologies no debe dejar una caja sobredimensionada');
assert.doesNotMatch(index, /Colegio Mixto|Bachillerato en Computaci/i, 'El portafolio no debe mostrar educaciÃ³n escolar');
assert.match(style, /\.education-grid\s*\{[^}]*max-width:\s*760px/i, 'Education debe concentrarse en el contenido relevante');
assert.equal((projectsSection.match(/class="project-proof"/g) || []).length, 3, 'Cada proyecto terminado debe explicar qué demuestra');
assert.match(index, /id="live-status"/i, 'Debe existir el módulo de estado NYXAND');
assert.match(index, /id="localTime"/i, 'El estado debe mostrar la hora local');
assert.match(index, /id="pageTime"/i, 'El estado debe mostrar el tiempo en la página');
assert.match(index, /id="githubActivity"/i, 'El estado debe reservar la actividad de GitHub');
assert.match(index, /id="githubEventTime"/i, 'El estado debe mostrar cuándo ocurrió la actividad');
assert.match(index, /id="githubEventMessage"/i, 'El estado debe reservar el mensaje del commit');
assert.match(index, /id="availabilityStatus"[^>]+aria-live="polite"/i, 'La disponibilidad debe anunciarse a lectores de pantalla');
assert.doesNotMatch(index, /Offline \/ no recent activity/i, 'El widget no debe sugerir inactividad sin contexto');
assert.match(main, /getDay\(\)/i, 'La disponibilidad debe considerar el dia de la semana');
assert.match(main, /21|04/, 'La disponibilidad debe contemplar el horario definido');
assert.match(main, /api\.github\.com\/repos\/AndrehhX\/NyxAnd-Portfolio\/commits\?per_page=1/i, 'El estado debe consultar el último commit del repositorio');
assert.doesNotMatch(main, /api\.github\.com\/users\/AndrehhX\/events/i, 'El estado no debe depender del feed retrasado de eventos');
assert.match(main, /setTimeout\(\(\) => controller\.abort\(\), 10000\)/i, 'La consulta de GitHub debe tolerar una respuesta lenta');
assert.match(main, /commit\?\.author\?\.date|commit\?\.committer\?\.date/i, 'El estado debe usar la fecha del commit');
assert.match(main, /commit\?\.commit\?\.message/i, 'El estado debe mostrar el mensaje del commit');
assert.doesNotMatch(main, /Bearer\s+|github[_-]?token/i, 'La actividad pública no debe requerir secretos');
assert.match(index, /id="nyxand-terminal"/i, 'Debe existir la terminal visual de NYXAND');
assert.match(index, /id="terminalInput"/i, 'La terminal debe tener una entrada de teclado');
assert.match(index, /id="terminalOutput"[^>]+aria-live="polite"/i, 'La salida de terminal debe ser accesible');
for (const command of ['help', 'about', 'projects', 'stack', 'status', 'contact', 'clear']) {
  assert.match(main, new RegExp(`['"]${command}['"]`, 'i'), `La terminal debe reconocer ${command}`);
}
assert.match(main, /initTerminal\(\)/, 'La terminal debe tener un inicializador propio');
assert.doesNotMatch(main, /child_process|window\.open\(['"]shell|eval\(/i, 'La terminal no debe ejecutar comandos reales');
assert.match(index, /id="nyxand-lab"/i, 'Debe existir el laboratorio de NYXAND');
assert.match(index, /id="labEditor"/i, 'El laboratorio debe tener un editor');
assert.match(index, /id="labPreview"[^>]+sandbox/i, 'La vista previa debe estar aislada en un iframe sandbox');
assert.doesNotMatch(index, /allow-scripts/i, 'El laboratorio no debe habilitar scripts en la vista previa');
assert.match(index, /id="labRun"/i, 'El laboratorio debe tener un control de ejecución');
assert.match(index, /id="labReset"/i, 'El laboratorio debe poder restaurar su ejemplo');
assert.match(index, /data-starter=/i, 'El laboratorio debe incluir ejemplos intercambiables');
assert.match(index, /data-starter="motion"/i, 'El laboratorio debe incluir un ejemplo de animaciones');
assert.match(main, /initLaboratory\(\)/, 'El laboratorio debe tener un inicializador propio');
assert.match(main, /motion:\s*`[\s\S]*?@keyframes/i, 'El ejemplo de animaciones debe incluir CSS real');
assert.match(main, /motion:[\s\S]*?animation:/i, 'El ejemplo de animaciones debe aplicar movimiento');
assert.match(main, /motion:[\s\S]*?prefers-reduced-motion/i, 'El starter de animaciones debe contemplar movimiento reducido');
assert.match(style, /\.terminal-window\s*\{[^}]*background:\s*var\(--white\)/i, 'La terminal debe seguir la paleta clara de NYXAND');
assert.match(style, /\.lab-editor-panel[\s\S]*?background:\s*var\(--white\)/i, 'El laboratorio debe evitar otro panel negro dominante');
assert.doesNotMatch(style, /\.terminal-window\s*\{[^}]*background:\s*var\(--black\)/i, 'La terminal no debe ser otro bloque negro');
assert.match(style, /@keyframes\s+statusCardReveal/i, 'Live debe tener una entrada propia');
assert.match(style, /@keyframes\s+signalPulse/i, 'Live debe tener una señal animada');
assert.match(style, /\.work-in-progress\s*\{[\s\S]*?background:\s*var\(--white\)/i);
assert.match(style, /@keyframes\s+wip/i, 'NEXUS debe tener una animación propia');
assert.match(index, /og:image" content="https:\/\/www\.nyxand\.site\/og-image\.svg/i, 'La vista social debe usar una imagen propia');
assert.match(index, /twitter:image/i, 'La vista social de Twitter debe tener imagen');
assert.doesNotMatch(index, /og:image" content="[^"]*favicon\.svg/i, 'El favicon no debe usarse como imagen social');

console.log('portfolio-content: ok');
